tau: 1.579591836734694
t_lower: 0.3877551020408163
t_upper: 0.8836734693877552
profile: balanced
lambda_fp: 5.0
lambda_fn: 5.0
lambda_unc: 2.0
metrics:
  coverage: 0.6733333333333333
  ok_rate: 0.9066666666666667
  accuracy_on_decided: 0.8613861386138614
  fp_accept_rate: 0.04666666666666667
  fn_reject_rate: 0.04666666666666667
  utility: -0.3605280528052805
