tau: 0.6271186440677967
t_lower: 0.0335593220338983
t_upper: 0.12745762711864406
lambda_fp: 10.0
lambda_fn: 10.0
lambda_unc: 1.0
max_fp_accept_rate: 0.05
max_fn_reject_rate: 0.05
max_fp_decided_upper95: 0.1
max_fn_decided_upper95: 0.1
min_coverage: 0.0
constraint_scope: both
enforce_decided_ci: false
tau_source: joint_grid
